docs: superlinked docs restructure
superlinked/sie pull request #68
Opened 2024-09-23 14:42 UTC by AruneshSingh

This PR contains a new `docs` subdirectory to store all documentation that is then shown at docs.superlinked.com

Changes
- New directory which follows the structure from [this](https://github.com/superlinked/superlinked-docs) repo, which is the basis for our [documentation](https://docs.superlinked.com/)
  - Read [this](https://github.com/superlinked/superlinked-docs/blob/main/how-this-works.md) for how it's setup
- Moving framework/reference to docs/reference, with some additional markdowns
- Removing markdown documentation from server, and adding to docs/run-in-production

The changes are done in order to have a single source of documentation, and not duplicate the contents inside docs/ and other subdirectories. 

Help required @estol 
- [ ] Update automation for creating framework/reference to now update docs/reference
- [ ] Add a github token to push changes from write.yaml workflow. (Advise if it should not be done through a personal fine grained access token)
- [ ] Would need tech team commitment to help keeping documentation upto date. (And consequent process changes, please advise where I can help) @kembala 

Once the PR is merged, @AruneshSingh updates the gitbook website to fetch data from this, instead of superlinked-docs repo.

2024-09-23 14:48 UTC, estol requested changes

2024-09-23 14:48 UTC, estol commented on .DS_Store
Please put this in a `.gitignore`.

2024-09-23 14:48 UTC, estol commented on .github/workflows/write.yaml
> +        git commit -m "Update docs/SUMMARY.md" || exit 0  # Exit 0 if no changes
All commits should be [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

2024-09-25 12:14 UTC, mamayer19 requested changes

2024-09-25 12:14 UTC, mamayer19 commented on .github/workflows/write.yaml
> +        GIT_AUTHOR_NAME: Arunesh Singh
We have `slrelease` as the CI technical user.

2024-09-25 12:14 UTC, mamayer19 commented on .github/workflows/write.yaml
> +      uses: ad-m/github-push-action@master
This doesn't work without permissions. Please indicate the needed permissions on a job level.
Docs: https://github.com/ad-m/github-push-action?tab=readme-ov-file#requirements-and-prerequisites

2024-09-25 12:14 UTC, mamayer19 commented on docs/scripts/set-reference.py
> +# new_references_to_write.append("* [DSL](reference/dsl)\n")
comment

2024-09-25 12:14 UTC, mamayer19 commented on .github/workflows/write.yaml
> +      uses: actions/checkout@v3
Old version
```suggestion
      uses: actions/checkout@v4
```

2024-09-25 12:14 UTC, mamayer19 commented on .github/workflows/write.yaml
> +        GITHUB_TOKEN: ${{ secrets.DATA_PUSH_TOKEN }}
In line with the previous comment about using `slrelease`, the token should also be that user's token or a repo/org secret.

2024-10-02 09:16 UTC, chirag-jn requested changes

2024-10-02 09:16 UTC, chirag-jn commented on .github/workflows/write.yaml
> +        fetch-depth: 0
We don't need the git history. `0` fetches the whole history of the `main` branch which would be time consuming. You can either set fetch-depth to `1` or remove the parameter itself since the default value is `1`

2024-10-02 09:31 UTC, AruneshSingh commented on .github/workflows/write.yaml
> +      uses: ad-m/github-push-action@master
Added a permission for the job, but this same action without the permissions worked in the current [docs](https://github.com/superlinked/superlinked-docs/blob/main/.github/workflows/write.yaml) repo.

2024-10-04 08:02 UTC, estol approved these changes

2024-10-04 08:21 UTC, mamayer19 approved these changes

2024-10-04 08:38 UTC, merged